### ISSUE TITLE
Figure and Caption Misalignment

### ISSUE THREAD

**Issue by delta-river** [wtsnjp/MioGatto#1]
As for the paper (id: 1808.02342), the figures and the captions are not correctly aligned.
The order of the figures is not wrong, however, still there are the following problems:
- the captions of figures are not correct (it looks like the caption for Fig 2 is skipped; thus, for Fig n(>1), caption for Fig (n-1) is corresponding to)
- Fig 15 is completely vanished from where it should be

**Comment by wtsnjp** [comment]
This was a problem for the dataset and nothing to do with MioGatto itself. The problem is resolved anyway.
