### ISSUE TITLE
Grounding情報源を示す地の色を変えてほしい

### ISSUE THREAD

**Issue by 3QUA9LA** [wtsnjp/MioGatto#18]
現在groundingを示す地の色について、ときどき見づらい色(黒っぽい、原色に近い)があり困っています。
この色を修正してほしいです。

色については、下記サイトの「パステルカラー」タブにあるものを使うとよいと思います。
https://www.colordic.org/p

**Comment by wtsnjp** [comment]
配色を変えたというよりも，単に情報源のハイライト色の「透過度」を上げてみました．こんな感じでマシになりますか？

<img width="681" alt="Screen Shot 2021-10-06 at 14 51 50" src="https://user-images.githubusercontent.com/9448125/136147811-22e6af9e-dda8-4a6f-b964-609f17fc22bf.png">
